# Generated by Django 4.2.23 on 2025-10-31 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_contact_number', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_employee', models.CharField(max_length=255)),
                ('employee_code', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('SUV', 'SUV'), ('Van', 'Van'), ('Bus', 'Bus'), ('Other', 'Other')], default='Car', max_length=20)),
                ('date_required', models.DateField(verbose_name='Date of Vehicle Required')),
                ('purpose', models.TextField(blank=True, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('assigned_transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='requests_app.transportcompany', verbose_name='Assigned Transport Company')),
            ],
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('asset_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tentative_vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('required_by_date', models.DateField(verbose_name='Required By Date')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
