# Generated by Django 4.2.23 on 2025-11-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='time_required',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Required'),
        ),
    ]
